"""DHIS2 live-query clients (CHAK server) and indicator specifications."""
from __future__ import annotations

import os
import re
import threading
import time

from services.superpower import _superpower_load_dict

# HIV+ category-option-combo ids (generated by _gen_coc_constants.py).  Every
# 'HTS_TST (facility) - … - HIV Testing' element shares the identical 52-COC
# set, so one flat list serves all of them.  This module is also imported by
# probe scripts launched from other working directories, hence the fallback.
try:
    from pbix_coc_constants import HIVPOS_COCS
except Exception:  # pragma: no cover
    try:
        import os as _os
        import sys as _sys
        _sys.path.insert(0, _os.path.dirname(_os.path.dirname(
            _os.path.abspath(__file__))))
        from pbix_coc_constants import HIVPOS_COCS
    except Exception:
        HIVPOS_COCS = {}

HTS_POSITIVE_COCS = sorted({c for cocs in HIVPOS_COCS.values() for c in cocs})


# ── CHAK DHIS2 config (for MOH 740 / MOH 731) ──────────────────────
CHAK_BASE = "https://ereporting.chak.or.ke/api"
CHAK_USER = "Johnbrian"
CHAK_PASS = "JOHNb123\\"

# ── CHAK transport resolution ───────────────────────────────────────
# CHAK retired the old plain-HTTP port 8500.  The same DHIS2 instance is now
# reached over TLS at https://ereporting.chak.or.ke/api — same server, same
# credentials — so that TLS URL is the single canonical base.
#
# CHAK_BASE is the built-in default, DHIS_BASE_URL may pin a different server
# (it wins over the default), and the last base that actually answered is
# remembered per process.  In a normal deployment every candidate is the same
# TLS URL.
#
# A base that raises a *connection* error is quarantined for a cooldown, so an
# unreachable host costs ONE ~4 s connect attempt per window instead of ~4 s on
# every single call.
_CHAK_LOCK = threading.Lock()
_CHAK_GOOD_BASE = None              # resolved winner, remembered per process
_CHAK_FAILED_AT = {}                # base -> time.monotonic() of last failure
_CHAK_COOLDOWN = float(os.getenv("CHAK_BASE_COOLDOWN", "120"))

# (connect, read).  Split so an unreachable host costs ~4 s instead of the full
# read budget; a *reachable* CHAK still needs a generous read timeout because
# its analytics queries legitimately take 10-35 s.
_CHAK_CONNECT_TIMEOUT = float(os.getenv("CHAK_CONNECT_TIMEOUT", "4"))
_CHAK_DEFAULT_READ_TIMEOUT = float(os.getenv("CHAK_READ_TIMEOUT", "240"))

# Read budgets for the two heavy analytics shapes.  Both are env-tunable so an
# operator can shorten them on a platform whose worker timeout is smaller than
# CHAK's worst-case latency.
_CHAK_ANALYTICS_READ_TIMEOUT = float(
    os.getenv("CHAK_ANALYTICS_READ_TIMEOUT", "120"))
_CHAK_COC_READ_TIMEOUT = float(
    os.getenv("CHAK_COC_READ_TIMEOUT", "240"))

# A base already inside its cooldown window is only being *probed* to notice
# CHAK recovering, so it must not re-pay a full 120/240 s budget.  A read
# timeout is a RequestException, so it is recorded as a failure too — before
# this cap, ONE blackholed call made every later call in the same build hang
# for the whole budget (measured: a single cold milestone build took 380 s).
_CHAK_PROBE_READ_TIMEOUT = float(
    os.getenv("CHAK_PROBE_READ_TIMEOUT", "6"))


def chak_bases():
    """Ordered CHAK base URLs: last known good, then the default, then env."""
    env_base = (os.getenv("DHIS_BASE_URL") or "").strip().rstrip("/")
    with _CHAK_LOCK:
        good = _CHAK_GOOD_BASE
    out = []
    for base in (good, CHAK_BASE, env_base):
        if base and base not in out:
            out.append(base)
    return out


def chak_get(path, params, read_timeout=None, auth=None):
    """GET a CHAK DHIS2 path, walking the candidate bases until one answers.

    `path` starts with '/'.  Returns the first response obtained from a
    *reachable* server — an HTTP 4xx/5xx is returned to the caller rather than
    triggering another base, because a server that rejects the query on one
    transport would reject it on the other too.

    Raises the last transport exception when no base is reachable, so each
    caller's existing `except` handling keeps working unchanged.
    """
    import requests as _req
    from requests.auth import HTTPBasicAuth

    global _CHAK_GOOD_BASE

    if auth is None:
        auth = HTTPBasicAuth(CHAK_USER, CHAK_PASS)
    # Caller-pinned read budget, else the generous default.  The heavy
    # analytics callers pass their own via _CHAK_ANALYTICS_READ_TIMEOUT /
    # _CHAK_COC_READ_TIMEOUT.
    want_read = read_timeout or _CHAK_DEFAULT_READ_TIMEOUT

    last_exc = None
    tried = []
    now = time.monotonic()
    candidates = chak_bases()

    def _in_cooldown(base):
        with _CHAK_LOCK:
            failed_at = _CHAK_FAILED_AT.get(base)
        return failed_at is not None and (now - failed_at) < _CHAK_COOLDOWN

    live = [b for b in candidates if not _in_cooldown(b)]
    if not live:
        # Everything is inside its cooldown window.  Now that there is
        # effectively ONE endpoint, refusing to try would black-hole every
        # request for the whole window, so probe anyway — a half-open retry
        # that recovers the moment CHAK is back.
        print("[DHIS2] all CHAK bases in cooldown; probing anyway "
              f"(read budget capped at {_CHAK_PROBE_READ_TIMEOUT:g}s for "
              f"{', '.join(candidates) or 'none'})")
        live = list(candidates)

    for base in live:
        url = base.rstrip("/") + path
        # Cap the read budget for a base we are only probing.  Without this
        # a base that just blackholed would be re-probed at the full
        # 120/240 s budget on every subsequent call in the same build.
        if _in_cooldown(base):
            timeout = (_CHAK_CONNECT_TIMEOUT,
                       min(want_read, _CHAK_PROBE_READ_TIMEOUT))
        else:
            timeout = (_CHAK_CONNECT_TIMEOUT, want_read)
        try:
            resp = _req.get(url, params=params, auth=auth, verify=False,
                            timeout=timeout)
        except _req.exceptions.RequestException as exc:
            with _CHAK_LOCK:
                _CHAK_FAILED_AT[base] = time.monotonic()
            last_exc = exc
            tried.append(f"{base} ({type(exc).__name__})")
            print(f"[DHIS2] CHAK base unreachable: {base} - "
                  f"{type(exc).__name__}: {exc}")
            continue
        with _CHAK_LOCK:
            _CHAK_GOOD_BASE = base
            _CHAK_FAILED_AT.pop(base, None)
        return resp

    print(f"[DHIS2] no reachable CHAK base (tried: {'; '.join(tried) or 'none'})")
    if last_exc is not None:
        raise last_exc
    raise ConnectionError("all CHAK base URLs are in cooldown")


def _normalize_pe(pe):
    """Coerce a period expression into the form DHIS2's `pe` dimension wants.

    DHIS2 periods are compact ("202606", "2026Q2", "2026") or relative
    ("LAST_12_MONTHS").  The single-month picker in the UI is an HTML
    ``<input type="month">``, which emits "2026-06" — DHIS2 silently returns
    **no rows** for that, so every single-month view rendered empty.  Collapse
    the YYYY-MM form (including each part of a semicolon-joined list) to YYYYMM.
    """
    if not pe:
        return pe
    txt = str(pe).strip()
    if ";" in txt:
        return ";".join(
            _normalize_pe(part) for part in txt.split(";") if part.strip()
        )
    if re.fullmatch(r"\d{4}-\d{2}", txt):
        return txt.replace("-", "")
    return txt


def _parse_dhis2_rows(rows, meta, coc_ids=None):
    """Parse DHIS2 analytics rows into a dict."""
    if not rows:
        return {}
    out = {}
    if coc_ids:
        # COC-disaggregated: keyed by (period, coc_id)
        # Row format: [dx, coc, pe, ou, value] when ou dimension is present
        for row in rows:
            if len(row) < 4:
                continue
            coc = str(row[1]) if len(row) > 1 else ""
            pe_code = str(row[2]) if len(row) > 2 else ""
            pe_name = meta.get(pe_code, {}).get("name", pe_code)
            val = float(row[-1]) if row[-1] else 0
            out[(pe_name, coc)] = out.get((pe_name, coc), 0) + val
    else:
        # Simple period-summed
        for row in rows:
            pe_code = str(row[1]) if len(row) > 1 else ""
            pe_name = meta.get(pe_code, {}).get("name", pe_code)
            val = float(row[-1]) if row[-1] else 0
            out[pe_name] = out.get(pe_name, 0) + val
    return out


def _dhis2_fetch(dx_ids, ou_id, pe="LAST_12_MONTHS", coc_ids=None):
    """Fetch analytics rows from DHIS2.
    Returns:
      - Without coc_ids: dict of {period_label: summed_value}
      - With coc_ids: dict of {(period_label, coc_id): value}
    dx_ids can be a single string or a list/set of strings.
    """
    from services.analytics_cache import get as cache_get, make_key, store as cache_set

    if isinstance(dx_ids, (list, set, tuple)):
        dx_str = ";".join(dx_ids)
    else:
        dx_str = dx_ids

    if not dx_str or not dx_str.strip():
        return {}  # no DX IDs to query

    pe = _normalize_pe(pe)

    # Build dimensions – ou_id can be a single ID or list
    if isinstance(ou_id, (list, set, tuple)):
        ou_str = ";".join(ou_id)
    else:
        ou_str = ou_id

    cache_key = make_key(dx_str, ou_str, pe, coc_ids, namespace="chak")
    hit = cache_get(cache_key)
    if hit is not None:
        return hit

    from requests.auth import HTTPBasicAuth

    username = os.getenv("DHIS_USERNAME", CHAK_USER)
    password = os.getenv("DHIS_PASSWORD", CHAK_PASS)
    auth = HTTPBasicAuth(username, password)

    dimensions = [f"dx:{dx_str}", f"pe:{pe}", f"ou:{ou_str}"]
    if coc_ids:
        if isinstance(coc_ids, (list, set, tuple)):
            coc_str = ";".join(coc_ids)
        else:
            coc_str = coc_ids
        dimensions.append(f"co:{coc_str}")

    params = {
        "dimension": dimensions,
        "displayProperty": "NAME",
    }
    # NOTE: this call used to try ai_translator's `fetch_query_result` first.
    # That was dead code — it returns rows shaped [{period, metric, facility,
    # value}] while `_parse_dhis2_rows` reads positional arrays, so the branch
    # always raised KeyError, was swallowed by `except Exception: pass`, and
    # fell straight through to here.  Its only effect was a SECOND full
    # analytics query per metric against an already slow CHAK server, so the
    # round-trip was removed rather than repaired.  (Superpower's parsed output
    # also drops the `co` dimension, so it could never have served the
    # COC-disaggregated callers anyway.)
    resp = chak_get("/analytics.json", params,
                    read_timeout=_CHAK_ANALYTICS_READ_TIMEOUT, auth=auth)
    if not resp.ok:
        return {}
    data = resp.json()
    rows = data.get("rows", [])
    meta = data.get("metaData", {}).get("items", {})
    parsed = _parse_dhis2_rows(rows, meta, coc_ids)
    cache_set(cache_key, parsed)
    return parsed


def _chak_analytics_fetch(dx_ids, ou_id, pe="LAST_12_MONTHS"):
    """Fetch analytics rows from CHAK DHIS2.
    Returns {dx_id: {period_name: value, ...}, ...}
    """
    from services.analytics_cache import get as cache_get, make_key, store as cache_set

    from requests.auth import HTTPBasicAuth

    from services.khis import _khis_parse_per_de

    auth = HTTPBasicAuth(CHAK_USER, CHAK_PASS)
    if isinstance(dx_ids, (list, set, tuple)):
        dx_str = ";".join(dx_ids)
    else:
        dx_str = dx_ids
    if not dx_str or not dx_str.strip():
        return {}
    if isinstance(ou_id, (list, set, tuple)):
        ou_str = ";".join(ou_id)
    else:
        ou_str = ou_id

    pe = _normalize_pe(pe)
    cache_key = make_key(dx_str, ou_str, pe, namespace="chak")
    hit = cache_get(cache_key)
    if hit is not None:
        return hit

    params = {
        "dimension": [f"dx:{dx_str}", f"pe:{pe}", f"ou:{ou_str}"],
        "displayProperty": "NAME",
    }
    try:
        resp = chak_get("/analytics.json", params,
                        read_timeout=_CHAK_ANALYTICS_READ_TIMEOUT, auth=auth)
        if not resp.ok:
            return {}
        data = resp.json()
        rows = data.get("rows", [])
        meta = data.get("metaData", {}).get("items", {})
        result = _khis_parse_per_de(rows, meta)
        cache_set(cache_key, result)
        return result
    except Exception:
        return {}


def _chak_analytics_fetch_coc(dx_id, ou_ids, pe="LAST_12_MONTHS",
                              name_prefixes=None, ou_chunk=100):
    """Fetch one CHAK data element by category option and keep only the
    options whose NAME starts with one of `name_prefixes`.

    CHAK DHIS2 2.40 ignores `co:<option-uid>` as a dimension filter — it
    returns the element's grand total regardless — so the element must be
    pulled with `co:categoryOptions` and filtered client-side on the
    category-option display name.

    Used for #9 IIT: 'C&T (facility) - Tx_ML, Outcomes' splits into Died /
    Transferred Out / Refused (Stopped) / Interruption (<3m, 3-5m, 6+m);
    only the 'Interruption' options are IIT.

    Returns {period_name: summed_value} — {} on any failure.
    """
    from services.analytics_cache import get as cache_get, make_key, store as cache_set

    from requests.auth import HTTPBasicAuth

    if isinstance(ou_ids, (list, set, tuple)):
        ou_list = list(ou_ids)
    else:
        ou_list = [ou_ids]
    ou_list = [str(o) for o in ou_list if o]
    if not ou_list:
        return {}

    prefixes = tuple(name_prefixes or ())
    pe = _normalize_pe(pe)
    cache_key = make_key(dx_id, ";".join(ou_list), pe, prefixes,
                         namespace="chak_coc")
    hit = cache_get(cache_key)
    if hit is not None:
        return hit

    auth = HTTPBasicAuth(CHAK_USER, CHAK_PASS)
    chunks = [ou_list[i:i + ou_chunk]
              for i in range(0, len(ou_list), ou_chunk)]

    def _one_chunk(chunk):
        """Fetch and parse a single OU chunk -> {period_name: summed_value}.

        Raises on transport/HTTP failure so the caller can abort the whole
        read: a silently dropped chunk would UNDER-count IIT, which is far
        worse than returning no data at all.
        """
        params = {
            "dimension": [f"dx:{dx_id}", "co:categoryOptions", f"pe:{pe}",
                          "ou:" + ";".join(chunk)],
            "paging": "false",
        }
        resp = chak_get("/analytics.json", params,
                        read_timeout=_CHAK_COC_READ_TIMEOUT, auth=auth)
        if not resp.ok:
            raise RuntimeError(f"CHAK COC fetch HTTP {resp.status_code}")
        data = resp.json()
        rows = data.get("rows", []) or []
        if not rows:
            return {}
        meta = data.get("metaData", {}).get("items", {})
        hdrs = [h.get("name") for h in (data.get("headers") or [])]
        try:
            co_i, pe_i = hdrs.index("co"), hdrs.index("pe")
            val_i = hdrs.index("value")
        except ValueError:
            co_i, pe_i, val_i = 1, 2, len(rows[0]) - 1
        part = {}
        for row in rows:
            if len(row) <= max(co_i, pe_i, val_i):
                continue
            name = (meta.get(str(row[co_i]), {}) or {}).get("name", "") or ""
            if prefixes and not name.startswith(prefixes):
                continue
            pe_name = (meta.get(str(row[pe_i]), {}) or {}).get(
                "name", str(row[pe_i]))
            try:
                val = float(row[val_i] or 0)
            except (TypeError, ValueError):
                continue
            part[pe_name] = part.get(pe_name, 0) + val
        return part

    # CHAK takes ~7-10 s per analytics request whatever its size, so the
    # chunks are fetched concurrently rather than back to back.  Results are
    # merged in the original chunk order, so the sum is identical to the
    # sequential path.
    from concurrent.futures import ThreadPoolExecutor

    out = {}
    with ThreadPoolExecutor(max_workers=min(4, len(chunks))) as ex:
        try:
            for part in ex.map(_one_chunk, chunks):
                for pe_name, val in part.items():
                    out[pe_name] = out.get(pe_name, 0) + val
        except Exception as exc:  # noqa: BLE001
            print(f"[DHIS2] CHAK COC fetch failed: {exc}")
            return {}
    cache_set(cache_key, out)
    return out


def _chak_analytics_coc_cells(dx_ids, ou_ids, pe="LAST_12_MONTHS",
                              ou_chunk=100):
    """Fetch data element(s) disaggregated by category option combo.

    Both Daraja funding namespaces share the SAME 30 age × sex COCs
    (`_COC_MALES` / `_COC_FEMALES`), so one request over
    `dx:kgzd9LfXZXq;aMp82zBYPnx` with `co:categoryOptions` yields the correct
    gender/age split for the whole 259-facility roster.

    Returns {period_name: {coc_uid: value}} — {} on any failure.
    """
    from services.analytics_cache import get as cache_get, make_key, store as cache_set

    from requests.auth import HTTPBasicAuth

    if isinstance(ou_ids, (list, set, tuple)):
        ou_list = [str(o) for o in ou_ids if o]
    else:
        ou_list = [str(ou_ids)] if ou_ids else []
    if not ou_list:
        return {}

    dx_key = dx_ids if isinstance(dx_ids, str) else ";".join(dx_ids)
    pe = _normalize_pe(pe)
    cache_key = make_key(dx_key, ";".join(ou_list), pe, namespace="chak_coc_cells")
    hit = cache_get(cache_key)
    if hit is not None:
        return hit

    auth = HTTPBasicAuth(CHAK_USER, CHAK_PASS)
    out: dict[str, dict[str, float]] = {}
    for i in range(0, len(ou_list), ou_chunk):
        params = {
            "dimension": [f"dx:{dx_key}", "co:categoryOptions", f"pe:{pe}",
                          "ou:" + ";".join(ou_list[i:i + ou_chunk])],
            "paging": "false",
        }
        try:
            resp = chak_get("/analytics.json", params,
                            read_timeout=_CHAK_COC_READ_TIMEOUT, auth=auth)
        except Exception as exc:  # noqa: BLE001
            print(f"[DHIS2] CHAK COC cells fetch failed: {exc}")
            return {}
        if not resp.ok:
            print(f"[DHIS2] CHAK COC cells fetch HTTP {resp.status_code}")
            return {}
        data = resp.json()
        rows = data.get("rows", []) or []
        if not rows:
            continue
        meta = data.get("metaData", {}).get("items", {})
        hdrs = [h.get("name") for h in (data.get("headers") or [])]
        try:
            co_i, pe_i = hdrs.index("co"), hdrs.index("pe")
            val_i = hdrs.index("value")
        except ValueError:
            co_i, pe_i, val_i = 1, 2, len(rows[0]) - 1
        for row in rows:
            if len(row) <= max(co_i, pe_i, val_i):
                continue
            co_uid = str(row[co_i])
            # NOTE: `meta` is keyed by uid for *every* dimension, so a COC
            # uid would also resolve here — always take the period from the
            # pe column, never from the COC.
            pe_name = (meta.get(str(row[pe_i]), {}) or {}).get("name")
            if not pe_name:
                pe_name = str(row[pe_i])
            try:
                val = float(row[val_i] or 0)
            except (TypeError, ValueError):
                continue
            bucket = out.setdefault(pe_name, {})
            bucket[co_uid] = bucket.get(co_uid, 0.0) + val
    cache_set(cache_key, out)
    return out


def _chak_coc_name_totals(dx_ids, ou_ids, pe="LAST_12_MONTHS",
                          include=("preg", "breast"), ou_chunk=100):
    """Sum data element(s) restricted to the PrEP *typology* COCs.

    The PBIX computes `PrEP New(PBFW)` and `PrEP Initiated ANC` by
    filtering the `PrEP New Total` element with

        'PrEP Typologies'[PrEP Typologies] IN {"Pregnant","Breastfeeding"}

    DHIS2 carries the same typology as the *third* token of the category
    option combo name (e.g. "20-24 years, Female, Breastfeeding"), so a
    case-insensitive substring match on the COC name reproduces that DAX
    exactly — no extra dimension request and no hard-coded COC uid list.

    `include` is the tuple of typology tokens to keep, lower-cased.

    Returns {period_name: value} — {} on any failure.  (Shaped like
    ``_dhis2_fetch`` so it can be dropped into the same metric loop.)
    """
    from services.analytics_cache import get as cache_get, make_key, store as cache_set

    from requests.auth import HTTPBasicAuth

    if isinstance(ou_ids, (list, set, tuple)):
        ou_list = [str(o) for o in ou_ids if o]
    else:
        ou_list = [str(ou_ids)] if ou_ids else []
    if not ou_list:
        return {}

    dx_key = dx_ids if isinstance(dx_ids, str) else ";".join(dx_ids)
    tokens = tuple(str(t).lower() for t in include)
    if not tokens:
        return {}
    pe = _normalize_pe(pe)
    cache_key = make_key(dx_key, ";".join(ou_list), pe, ",".join(tokens),
                         namespace="chak_coc_name_totals")
    hit = cache_get(cache_key)
    if hit is not None:
        return hit

    auth = HTTPBasicAuth(CHAK_USER, CHAK_PASS)
    out: dict[str, float] = {}
    for i in range(0, len(ou_list), ou_chunk):
        params = {
            "dimension": [f"dx:{dx_key}", "co:categoryOptions", f"pe:{pe}",
                          "ou:" + ";".join(ou_list[i:i + ou_chunk])],
            "paging": "false",
        }
        try:
            resp = chak_get("/analytics.json", params,
                            read_timeout=_CHAK_COC_READ_TIMEOUT, auth=auth)
        except Exception as exc:  # noqa: BLE001
            print(f"[DHIS2] CHAK typology fetch failed: {exc}")
            return {}
        if not resp.ok:
            print(f"[DHIS2] CHAK typology fetch HTTP {resp.status_code}")
            return {}
        data = resp.json()
        rows = data.get("rows", []) or []
        if not rows:
            continue
        meta = data.get("metaData", {}).get("items", {})
        hdrs = [h.get("name") for h in (data.get("headers") or [])]
        try:
            co_i, pe_i = hdrs.index("co"), hdrs.index("pe")
            val_i = hdrs.index("value")
        except ValueError:
            co_i, pe_i, val_i = 1, 2, len(rows[0]) - 1
        for row in rows:
            if len(row) <= max(co_i, pe_i, val_i):
                continue
            co_name = (meta.get(str(row[co_i]), {}) or {}).get("name", "")
            low = str(co_name).lower()
            if not any(t in low for t in tokens):
                continue
            pe_name = (meta.get(str(row[pe_i]), {}) or {}).get("name")
            if not pe_name:
                pe_name = str(row[pe_i])
            try:
                val = float(row[val_i] or 0)
            except (TypeError, ValueError):
                continue
            out[pe_name] = out.get(pe_name, 0.0) + val
    cache_set(cache_key, out)
    return out


def _find_dx_by_pattern(prefix_pattern, age_bands):
    """Find male & female DX IDs from the data element dictionary.
    prefix_pattern: e.g. 'Tx_New STA' or 'TX_Curr STA'
    age_bands: list of strings like ['<1','1-4',...]
    Returns (males_list, females_list) of 11-char UIDs each.
    """
    try:
        df_elements, _ = _superpower_load_dict()
    except Exception:
        return [], []
    names = df_elements["name"].astype(str)
    males, females = [], []
    for age in age_bands:
        # Handle both "Tx_New STA <1M" (no comma) and "TX_Curr STA <1,M" (comma)
        pat_m = rf"{prefix_pattern}\s+{age},?\s*M\b"
        pat_f = rf"{prefix_pattern}\s+{age},?\s*F\b"
        m_match = df_elements[names.str.match(pat_m, case=False, na=False)]
        f_match = df_elements[names.str.match(pat_f, case=False, na=False)]
        if not m_match.empty:
            males.append(m_match.iloc[0]["id"])
        if not f_match.empty:
            females.append(f_match.iloc[0]["id"])
    return males, females


# ── Indicator specs for each subtab type ───────────────────────────
# DX IDs verified against dictionaries/master_data_elements.csv (2025-06-28)
# ── COC IDs for "Finer Age Bands and Gender" category combo ──────
# Age bands → Category Option Combo IDs (verified against CHAK DHIS2)
_COC_MALES = [
    "AwerOu6rx5q","g2zP3yNwOOa","WTfu1bBSG12","X65JamO5tyb","hKHprPKwjL6",
    "uSDHHGh2DZo","sLaLEIDVusT","b91xfEPrY4D","EU7hVFz5Yyt","AR2E4Yiuo8Z",
    "dfkyp7ZQZSr","lswMoqT008e","Z6zV5L8i14I","XIc55yRW4aQ","g5bVF4b8hmV",
]  # <1,M  1-4,M  5-9,M  10-14,M  15-19,M  20-24,M  25-29,M  30-34,M  35-39,M  40-44,M  45-49,M  50-54,M  55-59,M  60-64,M  65+,M
_COC_FEMALES = [
    "dcv8Lowu94w","D2aMSzo7SEw","HIS0TcFAoo8","Rr3uh3eAvKi","DYDpnZWu1XK",
    "m7Y0ddB212k","qy1vJGvFJeB","sk5UiD3PrxH","Vb7KzTvF83C","dchngmvBGvb",
    "VP1zCgdzuBb","uefSjW3VtZr","llt7APqVWyq","gs3y2muDLIK","YAtW6LDL24J",
]  # <1,F  1-4,F  5-9,F  10-14,F  15-19,F  20-24,F  25-29,F  30-34,F  35-39,F  40-44,F  45-49,F  50-54,F  55-59,F  60-64,F  65+,F

# Age band labels in the same positional order as the two COC lists above.
COC_AGE_BANDS = [
    "<1", "1-4", "5-9", "10-14", "15-19", "20-24", "25-29", "30-34",
    "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65+",
]
# coc uid -> (age band, sex)  — sex is "M" or "F"
COC_CELL_MAP = {}
for _band, _uid in zip(COC_AGE_BANDS, _COC_MALES):
    COC_CELL_MAP[_uid] = (_band, "M")
for _band, _uid in zip(COC_AGE_BANDS, _COC_FEMALES):
    COC_CELL_MAP[_uid] = (_band, "F")

# ── Daraja project split: Jamii Tekelezi (187) vs CHAP Stawisha (62) ──
# The 259-facility Daraja roster reports into TWO mutually-exclusive DHIS2
# attribute option combos (funding mechanisms / reporting datasets):
#   • 84477 – USAID Jamii Tekelezi  (AOC T1rTe8Xa4CX) → 187 facilities
#   • 85745 – CHAP Stawisha         (AOC vZjyS5WF2aV) →  62 facilities
# For any given period the overlap between the two AOCs is ZERO, so a
# metric's true value is the UNION of both namespaces.  This mirrors the
# PBIX DAX pattern COALESCE(<jamii>,0) + COALESCE(<stawisha>,0).
# Every id below was verified live against CHAK DHIS2 (period 202607).
_STA_TX_CURR = "aMp82zBYPnx"                                   # TX_CURR Patients on Care
_STA_TX_NEW = ["Syg8KH15VW6", "gxEX3f1Wi4i", "r2X4WnVpKQG"]     # CD4 <200 / >200 / unknown
_STA_TX_NEW_CD4_LT200 = "Syg8KH15VW6"
_STA_TX_NEW_CD4_GE200 = "gxEX3f1Wi4i"
_STA_VL_DEN = ["XfG4IcrxsAL", "ya8yqHMBz1z",                    # <50 | 50-199
               "JkR9WcfccpF", "Ub1rdwX3AQK"]                     # 200-399 | >1000 cps/ml
_STA_VL_NUM = ["XfG4IcrxsAL", "ya8yqHMBz1z", "JkR9WcfccpF"]
# The 62's ART regimen split.  The old "C&T (facility) - ART Regimen
# Monitoring" ids returned 0 for BOTH projects; these are the live twins.
_STA_TX_CURR_REGIMEN = [
    ("On DTG 1st Line", "JOldQxWZWso"),
    ("On DTG 2nd Line", "HzXPYZqLgqj"),
    ("On EFV", "wJ0vH5TRFHw"),
    ("On PI 1st Line", "EgNQnR23En1"),
    ("On PI 2nd Line", "KsDSjjJo6GD"),
    ("On RAL 1st Line", "VIz7xRli13H"),
    ("On RAL 2nd Line", "KEAYcGVL6Bk"),
    ("On Third Line", "qDjo1L1VfmP"),
]
# The 62's HTS testing + new-positive elements (PITC / ANC / SNS / PAEDS / MALN / FP).
_STA_HTS_TESTED = [
    "FeL9n4JPBwR", "U5p3md08al7", "z4SijuAuj8u", "EBUHaKNgr76",
    "m0TGh0x0BKG", "eIgi7HI0dHC", "EbemQ1YUsS4", "geC2CBzyQme",
    "JEOphdexA5h", "oRcQ7WvMSbg", "GpUsEYocjeF", "n1gIS3iRf5b",
    "iWTSCEnAzth", "ZMvTVuvnujj", "sE6Fiu7oCWG", "dkX4EY6cwl9",
    "U60JE807fKl", "Zc6u4IbiDtI", "DR7CJrCb99O", "qfGXWJ4dyfq",
    "lU61bvd4vFS", "qrOHMHfq6vW", "fan1vuTrnfZ", "lm2vXVEzxgd",
    "WFBz2SqHikz", "F2vqHaV3SIV", "DDYp26Y2pLU", "j1Ovy0UzWKC",
]
_STA_HTS_POSITIVE = [
    "AqIZwh2gOUs", "FNCubo2RFGW", "Cwn1ZLCXt6B", "fryB6XsrdEX",
    "WgrVvWg6CEI", "xZvJ5UT2EK2", "BIQZfMkMzr6", "ObNBXpybAaC",
    "FX0DHPMp83V", "BhnzHXFnEM3", "iOfdKICx6r9", "b6RjSYPtLvy",
    "ztdFfMQWrSF", "S6KQd8Rmjad", "doYJQ4Ieqc7", "g3NOJTsqayy",
    "LdO5qX5j238", "SBGWvCJYoHl", "wrU23YQYX0l", "wuNiGmPCvjF",
    "MADCCrhi2wC", "jO8zNMIrakZ", "hzRWjr4PtME", "BpItig3EWij",
    "R9mc3S56hWD", "jbyp2irkHnt", "KhG8T1IxFNF", "HvXNwm2FiDE",
]
# DHIS2 indicator numerators the Jamii (previous) project reports through.
_IND_HTS_TST_NUM = "MSdR6p2OEmx"        # HTS_TST : Numerator
_IND_HTS_TST_POS_NUM = "smzxVpKXbR5"    # HTS_TST_POS : Numerator

# ── The Daraja "tested" universe ──────────────────────────────────
# The PBIX report measure "HTS Tested 1" sums exactly these 17 Jamii
# HTS_TST elements:
#     8 x HTS_TST (facility) entry points
#   + 7 x PMTCT (ANC1 Only / ANC Initial / ANC Retests / L&D / L&D
#          Retests / PNC / PNC Retests)
#   + 2 x SNS tested peers (HRN + Pos)
# The 28 Stawisha "... New Positive"-family elements that used to be
# appended here belong to the separate 62-facility project namespace
# and are NOT part of the Daraja/Jamii result: including them both
# dropped the PMTCT/SNS activity and added foreign activity.
# Verified: this equals CHAK's own DHIS2 indicator MSdR6p2OEmx
# ("HTS_TST : Numerator") and reproduces the reported figure for Meru
# County 2026-06 -> 7,236 tested.
_HTS_TST_JAMII_17 = [
    "J4zibSjbBCt",  # HTS_TST (facility) - VCT - HIV Testing
    "THJbtDzxplR",  # HTS_TST (facility) - PITC Inpatient Services
    "XKAlilawdhN",  # HTS_TST (facility) - PITC Emergency
    "QBsyLQZRdiH",  # HTS_TST (facility) - STI clinic
    "vFlUDposW0Y",  # HTS_TST (facility) - Other PITC
    "XYhYAMivUX5",  # HTS_TST (facility) - TB Clinic
    "ymKviaHZtQN",  # HTS_TST (facility) - Malnutrition clinic
    "Lwtqyjus0Mb",  # HTS_TST (facility) - PITC Pediatric Services
    "bMmnawX0lJZ",  # HTS_TST (facility) - PMTCT ANC1 Only
    "GT0exFOJBb6",  # HTS_TST (facility) - PMTCT ANC Initial @2,3,4,.. Visits
    "VUddRU5XXhi",  # HTS_TST (facility) - PMTCT ANC Retests
    "QJEM1kwtmEc",  # HTS_TST (facility) - PMTCT L&D
    "QHNavEKSTse",  # HTS_TST (facility) - PMTCT L&D Retests
    "NO3wqVVZ0Ax",  # HTS_TST (facility) - PMTCT PNC
    "jWdJvSe5eh4",  # HTS_TST (facility) - PMTCT PNC Retests
    "MGZ0ACvFX2q",  # SNS (HRN) - Tested peers
    "FITo7mucBoA",  # SNS (Pos) - Tested peers
]

# ── HTS testing: the PBIX's TWO project sections ───────────────────
# Every testing visual in the report is bound to the measure `HTS Tested`,
# whose DAX reads:
#     VAR _OurProjectElements   = { 17 Jamii / Daraja elements }   (JTP)
#     VAR _OtherProjectElements = { 28 CHAP Stawisha elements }
#     VAR _CombinedElements     = UNION(_OurProjectElements, _OtherProjectElements)
#     RETURN CALCULATE(SUM('Data Element Values'[Value]),
#                      'Data Elements'[Data Element] IN _CombinedElements)
# i.e. it ADDS BOTH projects.  Verified by reading the report layout itself
# (Report/definition/pages/**/visual.json): `HTS Tested` is on "Total tested
# for HIV Monthly Performance" (lineChart), "TESTING TREND BY COUNTY",
# "Total tested by Sex" / "by Age" and the HTS performance cards.  No visual
# in the report references the our-project-only measure `HTS Tested 1`.
#
# The two namespaces are also disjoint at facility level, so the union cannot
# double count: for 202606 the entire 7,187 of the 28-element total sits on
# the 62 CHAP Stawisha facilities and exactly 0 on the other 197.
HTS_TESTED_OUR = list(_HTS_TST_JAMII_17)              # 17 x JTP (Jamii/Daraja)
HTS_TESTED_OTHER = list(_STA_HTS_TESTED)              # 28 x CHAP Stawisha
HTS_TESTED_ALL = HTS_TESTED_OUR + HTS_TESTED_OTHER    # 45 = PBIX `HTS Tested`

# The same two sections for positives.  The PBIX measure is
# `HTS_Testing_Positives` = the SAME element list as `HTS_Testing_General`
# wrapped in `KEEPFILTERS('HIV Results'[HIV Results] == "HIV+")`, so the JTP
# half is the 15 `HTS_TST (facility) - *` elements CUT TO THEIR HIV+ CATEGORY
# OPTION COMBOS, plus the SNS "(Pos) - Tested peers" element (its name already
# means positive, so it must NOT be COC-filtered).  The Stawisha half is the
# 28 "... New Positive" elements, which also bake positivity into the name.
#
# 🔥 `smzxVpKXbR5` ("HTS_TST_POS : Numerator") is NOT this measure.  It is a
# standalone DHIS2 *indicator* whose numerator does not equal the 15 facility
# elements @ HIV+ (221 vs 245 for all counties @202606), so using it made the
# HIV Testing page show 366 positives where the PBIX shows 390 — a 24-record
# under-report, and a different number from `/pbix/api/hts-summary` for the
# very same metric.  Same defect `pbix_dashboards._hts_positive_periods`
# already documents and avoids.
HTS_POSITIVE_OUR15 = list(_HTS_TST_JAMII_17[:15])     # 15 x HTS_TST (facility)
# SNS "(Pos) - Tested peers" ONLY — the HRN twin counts *tested* peers, not
# positives, and the 15 facility elements above exclude both by construction.
# Matches `pbix_dashboards.HTS_POSITIVE_SNS`.
HTS_POSITIVE_SNS = ["FITo7mucBoA"]
HTS_POSITIVE_OUR = HTS_POSITIVE_OUR15                 # needs HTS_POSITIVE_COCS
HTS_POSITIVE_OTHER = list(_STA_HTS_POSITIVE)          # 28 x CHAP Stawisha
HTS_POSITIVE_ALL = (HTS_POSITIVE_OUR + HTS_POSITIVE_SNS
                    + HTS_POSITIVE_OTHER)             # 44 = PBIX `HTS Positive`

INDICATOR_SPECS = {
    "tx_new": {
        "title": "Newly Started on ART",
        # Jamii "TX_NEW: Starting ART" (already CD4-decomposed) + the
        # Stawisha CD4 <200 / >200 / unknown triplet.  AOCs never overlap.
        "aggregate": ";".join(["vTTEybkXZ53"] + _STA_TX_NEW),
        "male_cocs": _COC_MALES,
        "female_cocs": _COC_FEMALES,
        "age_bands": ["<1","1-4","5-9","10-14","15-19","20-24",
                      "25-29","30-34","35-39","40-44","45-49",
                      "50-54","55-59","60-64","65+"],
        "color_total": "#2563eb",
        "color_male": "#10b981",
        "color_female": "#ec4899",
    },
    "tx_curr": {
        "title": "Current on ART",
        # PBIX measure `TX_CURR`:
        #   _OurProject   = "TX_CURR"                         (Jamii)
        #   _OtherProject = the 8 "TX_CURR on <regimen line>"  (the 62)
        # It is NOT "TX_CURR Patients on Care" (aMp82zBYPnx): that is a
        # separate MER element the PBIX never sums here.  Including it
        # added 5 phantom clients for Meru 2026-06 (6,364 vs the 6,359
        # the regimen lines actually report).
        # Both halves share the standard 30 age x sex COCs, so the total
        # and the M/F split remain additive:
        #   Meru 2026-06 -> 22,840 = F 15,442 + M 7,398
        "aggregate": ";".join(["kgzd9LfXZXq"] +
                              [u for _lbl, u in _STA_TX_CURR_REGIMEN]),
        "male_cocs": _COC_MALES,
        "female_cocs": _COC_FEMALES,
        "age_bands": ["<1","1-4","5-9","10-14","15-19","20-24",
                      "25-29","30-34","35-39","40-44","45-49",
                      "50-54","55-59","60-64","65+"],
        "color_total": "#7c3aed",
        "color_male": "#10b981",
        "color_female": "#ec4899",
    },
    "vl": {
        "title": "VL Monitoring",
        # Jamii "VL Monitoring (All): TX_PVLS (D) Routine" + the Stawisha
        # VL result bands (<50 / 50-199 / 200-399 / >1000 cps/ml).
        "aggregate": ";".join(["JGd3MwmKBuM"] + _STA_VL_DEN),
        "color_total": "#0891b2",
        "vl_pvls_d": ";".join(["JGd3MwmKBuM"] + _STA_VL_DEN),
        # Suppressed = <1000 cps/ml → <50 + 50-199 + 200-399.
        "vl_pvls_n": ";".join(["FloZph8hN9z"] + _STA_VL_NUM),
    },
}

# ── Daraja Treatment subtab specs ──────────────────────────────────
# Data elements from the JTP Monthly HIV Care and Treatment dataset
DARAJA_SPECS = {
    "art_optimization": {
        "title": "ART Optimization",
        "metrics": {
            "regimen_1st_line": {"ids": ["zZGNba5d34c"], "label": "TX_CURR on 1st Line"},
            "regimen_2nd_line": {"ids": ["F0xtjHxDZ2e"], "label": "TX_CURR on 2nd Line"},
            "regimen_3rd_line": {"ids": ["Pk1PMmG4ml7"], "label": "TX_CURR on 3rd Line"},
            "on_dtg": {"ids": ["s62uidROGjG"], "label": "TX_CURR on DTG"},
            "eligible_dtg": {"ids": ["bsQdHW8sJ4b"], "label": "Eligible for DTG"},
            "efv_600": {"ids": ["lr1YorhNrJT"], "label": "Active on EFV-600"},
            "efv_400": {"ids": ["ggO3YzjB9j4"], "label": "Active on EFV-400"},
            "pi_based": {"ids": ["Z4g3jskQn9c"], "label": "Active on PI Regimen"},
            "viremia_clinic": {"ids": ["JGIZOGP6bGU"], "label": "Active in Viremia Clinic"},
        },
    },
    "dsd": {
        "title": "Differentiated Service Delivery (DSD)",
        "metrics": {
            "eligible_dc": {"ids": ["zkZIEcm0mFs"], "label": "Eligible for DC"},
            "on_dc": {"ids": ["qfLHg1lbN3W"], "label": "Clients Put on DC"},
            "eligible_dcm": {"ids": ["oJfkiD0C599"], "label": "Eligible for DCM"},
            "dcm_community": {"ids": ["oHTbEMaKn7L"], "label": "DCM - Community"},
            "dcm_facility": {"ids": ["cPEthRR8Zs1"], "label": "DCM - Facility"},
            "arv_dispensing": {"ids": ["Lo3GoG3lxOF"], "label": "ARV Dispensing"},
        },
    },
    "treatment_outcomes": {
        "title": "Treatment Outcomes",
        "metrics": {
            "iit_3m": {"ids": ["Cn2q8OMIHDD"], "label": "IIT > 3 Months"},
            "iit_1m": {"ids": ["Gg3ZzBADtz8"], "label": "IIT <= 3 Months"},
            "stopped": {"ids": ["HjRScpxwVQn"], "label": "Stopped Treatment"},
            "died": {"ids": ["DrtGJ1cgA3J"], "label": "Died this Month"},
            "transfers_out": {"ids": ["YX65zEg6s5R"], "label": "Transferred Out"},
            "transfers_in": {"ids": ["vODolOs8eBi"], "label": "Transferred In"},
            "rtt": {"ids": ["tCFth5mfGz5"], "label": "Return to Treatment (RTT)"},
        },
    },
    "otz": {
        "title": "OTZ (O and Teen Club)",
        "metrics": {
            "booked": {"ids": ["ep6NJHQ9LJa"], "label": "OTZ Booked"},
            "adher_95": {"ids": ["kMe6SRtZ6pn"], "label": "Adherence >95%"},
            "basevl_lt1000": {"ids": ["O6wVcguUXbQ"], "label": "Baseline VL <1000"},
            "basevl_lt200": {"ids": ["caFpNcJu2q2"], "label": "Baseline VL <200"},
            "basevl_ldl": {"ids": ["JFfFnMNV2dL"], "label": "Baseline VL LDL"},
        },
    },
    "ovc": {
        "title": "OVC (Orphans and Vulnerable Children)",
        "metrics": {
            "calhiv_enrolled": {"ids": ["Ml7NYiKXKJ9"], "label": "CALHIV OVC Enrolled"},
            "prev_15_24": {"ids": ["d7PKefTNRPT"], "label": "ICT PREV 15-24yrs"},
            "prev_lt15": {"ids": ["jgtv4fG2Vpm"], "label": "ICT PREV <15yrs"},
            "prev_gt25": {"ids": ["s8sJolX8W8I"], "label": "ICT PREV >25yrs"},
            "ovc_hivstat": {"ids": ["vd42QeUMvb2"], "label": "OVC HIV Status Known"},
            "ovc_serv": {"ids": ["CNdhjjVHiHp"], "label": "OVC Services"},
        },
    },
    "covid": {
        "title": "COVID-19",
        "metrics": {
            "screened": {"ids": ["z4ylGRyQ7Rl"], "label": "CCC Screened for COVID"},
        },
    },
    "ahd": {
        "title": "Advanced HIV Disease (AHD)",
        "metrics": {
            "kepi": {"ids": ["g0s65Dm47CA"], "label": "CALHIV KEPI"},
            "not_imm": {"ids": ["oWSf2zNhstC"], "label": "CALHIV Not Immunized"},
            "pneumo": {"ids": ["vFByuxLPFX7"], "label": "CALHIV Pneumo"},
            "rota": {"ids": ["iBsCVgCGyQ7"], "label": "CALHIV Rota"},
            "cd4_smearpos": {"ids": ["R5KyL0fYJle"], "label": "CD4 TB Smear+"},
            "iit_cd4": {"ids": ["KRvAhAQ5O46"], "label": "IIT CD4"},
            "iit_cd4_lt200": {"ids": ["rrfFv94aqgy"], "label": "IIT CD4 <200"},
        },
    },
    "adverse_events": {
        "title": "Adverse Events (AE)",
        "metrics": {
            "cod_tb": {"ids": ["LIvYFVNx00M"], "label": "COD - TB"},
            "cod_cancer": {"ids": ["RlKpuE0qv0q"], "label": "COD - Cancer"},
            "cod_other_hiv": {"ids": ["ZnmeKVBraIA"], "label": "COD - Other HIV Disease"},
            "cod_other_natural": {"ids": ["hgV3WXdiPbZ"], "label": "COD - Other Natural Causes"},
            "cod_non_natural": {"ids": ["Lw7SrH10igs"], "label": "COD - Non Natural Causes"},
            "cod_unknown": {"ids": ["yrERSv923Qh"], "label": "COD - Unknown Causes"},
        },
    },
}

# ── HTS (HIV Testing Services) indicator specs ────────────────────
HTS_SPECS = {
    "hts_uptake": {
        "title": "HIV Testing Services Uptake",
        "metrics": {
            # Two project sections, exactly as the PBIX `HTS Tested` /
            # `HTS Positive` measures split them.  The endpoint adds them back
            # into `hts_tested` / `hts_positive` so the existing UI contract is
            # unchanged, while the halves stay individually attributable.
            "hts_tested_our": {
                "ids": HTS_TESTED_OUR,
                "label": "Tested - JTP (Jamii/Daraja)",
                "split": True,
            },
            "hts_tested_other": {
                "ids": HTS_TESTED_OTHER,
                "label": "Tested - CHAP Stawisha",
                "split": True,
            },
            "hts_positive_our": {
                # 15 x `HTS_TST (facility) - *` restricted to the HIV+ COCs,
                # plus the SNS "(Pos) - Tested peers" element (no COC filter).
                "ids": HTS_POSITIVE_OUR,
                "cocs": HTS_POSITIVE_COCS,
                "extra_ids": HTS_POSITIVE_SNS,
                "label": "Positive - JTP (Jamii/Daraja)",
                "split": True,
            },
            "hts_positive_other": {
                "ids": HTS_POSITIVE_OTHER,
                "label": "Positive - CHAP Stawisha",
                "split": True,
            },
        },
        # hts_tested / hts_positive / positivity_rate computed in endpoint
    },
    "hts_linkage": {
        "title": "HIV Testing Services Linkage",
        "metrics": {
            # All seven HTS_TST (facility) modalities — the old lists only
            # carried Malnutrition / Other PITC / PITC Emergency, so the
            # linkage cascade under-counted.
            "linked_within": {
                "ids": ["wQ5AA7GTs9G",     # Malnutrition clinic
                        "YroUdlNVeR2",     # Other PITC
                        "h13L1gcUaCS",     # PITC Emergency
                        "CafkDRu8dxj",     # PITC Inpatient Services
                        "bLkDbbGXFi9",     # PITC Pediatric Services
                        "gfpnQkyZahY",     # STI clinic
                        "T5RKa6280JP"],    # VCT
                "label": "Linked Within Facility",
            },
            "linked_outside": {
                "ids": ["DdPzCAtN3J2",     # Malnutrition clinic
                        "ZnetI7sd8Ub",     # Other PITC
                        "BeO9dmxTBMg",     # PITC Emergency
                        "RexTMiW9ZoW",     # PITC Inpatient Services
                        "kylYPTvwl8j",     # PITC Pediatric Services
                        "snxbZLLB8lq",     # STI clinic
                        "HO7lHck9slY"],    # VCT
                "label": "Linked Outside Facility",
            },
            "total_tested": {
                "ids": HTS_TESTED_ALL,
                "label": "Total Tested (Ref)",
            },
        },
    },
    "partner_notification": {
        "title": "Partner Notification Services",
        "metrics": {
            "index_offered": {
                "ids": ["gp0RYhjsc1f"],
                "label": "Index Clients Offered PNS",
            },
            "index_accepted": {
                "ids": ["sTBggmuuiGR"],
                "label": "Index Clients Accepting PNS",
            },
            "contacts_tested": {
                "ids": ["DtJ8Kpaquhx"],
                "label": "Contacts Tested",
            },
        },
    },
    "prep": {
        "title": "PrEP",
        "metrics": {
            # PBIX measure `PrEP New Total`:
            #   SET = { "PrEP_New: PrEP, New Clients",
            #           "PREP New AGYW", "PREP New BF", "PREP New FSW",
            #           "PREP New MSM",  "PREP New OMHR", "PREP New OWHR",
            #           "PREP New PG",   "PREP New PWID", "PREP New SDC",
            #           "PREP New TG" }
            # The old list mixed in 15 `PREP_ALLMod ...` elements which the
            # PBIX never references (they also inflated the total by +33
            # for Meru 2026-06).  Trimmed to the PBIX eleven.
            "prep_new": {
                "ids": [
                    "VIg3ciXYUQn",  # Jamii  PrEP_New: PrEP, New Clients
                    "Nz7EhR18YMK",  # PREP New AGYW
                    "S8VvgOzJRkX",  # PREP New BF
                    "EYOQtTc1Luo",  # PREP New FSW
                    "JkV3QDZblU8",  # PREP New MSM
                    "mSLKtkUIiXu",  # PREP New OMHR
                    "ZVlWaa7hQyp",  # PREP New OWHR
                    "KFp4UYTJ4Q6",  # PREP New PG
                    "mOMfbne0htO",  # PREP New PWID
                    "KUfbLJCGou7",  # PREP New SDC
                    "m8E8rIRW8XH",  # PREP New TG
                ],
                "label": "PrEP New",
            },
            # PBIX has no "PrEP Current" measure.  The nearest PBIX-named
            # analogue is the Stawisha `PREP Continuing <typology>` family
            # (the Jamii side reports no continuing-client element at all),
            # so this metric is explicitly the Other-Project half and must
            # not be presented as a combined figure.
            "prep_curr": {
                "ids": [
                    "UXGOZdm9wA7",  # PREP Continuing AGYW
                    "ogOSIjGiRj2",  # PREP Continuing BF
                    "w7Sd9JLas99",  # PREP Continuing FSW
                    "wiUVuc4bOPU",  # PREP Continuing MSM
                    "soKdbhywZvM",  # PREP Continuing OMHR
                    "jJD6Qbx4Jft",  # PREP Continuing OWHR
                    "rcVQa6PY6Gj",  # PREP Continuing PG
                    "Vcg2VrsiXMV",  # PREP Continuing PWID
                    "RiKtBB2ZMnL",  # PREP Continuing SDC
                    "HzfaxOT0UND",  # PREP Continuing TG
                ],
                "label": "PrEP Current (Stawisha)",
            },
            # PBIX measure `PrEP Screening Total` (line 1961):
            #   CALCULATE(SUM(Value),
            #       'Data Elements'[Data Element] =
            #           "PrEP_Screening: PrEP, New Clients")
            # i.e. the SINGLE Jamii element kLWYCIQyIpS.  An earlier comment
            # here claimed the measure coalesced an "other project" restart
            # element — the DAX says otherwise: restart clients are their own
            # element and are NOT part of this measure.  Adding S1rCBFjMF3E
            # showed 3,121 for Meru 2026-06 where the report shows 3,105.
            "prep_screened": {
                "ids": [
                    "kLWYCIQyIpS",  # PrEP_Screening: PrEP, New Clients
                ],
                "label": "PrEP Screened",
            },
            # PrEP_Screening: PrEP, Restart Clients — a separate element the
            # PBIX reports on its own (it has no dedicated measure, so expose
            # it standalone rather than folding it into the total above).
            "prep_screened_restart": {
                "ids": [
                    "S1rCBFjMF3E",  # PrEP_Screening: PrEP, Restart Clients
                ],
                "label": "PrEP Screened (Restart)",
            },
            # PBIX `PrEP New(PBFW)` = [PrEP New Total] where
            # 'PrEP Typologies'[PrEP Typologies] IN {"Pregnant",
            # "Breastfeeding"}.  The Jamii half needs the typology filter
            # (handled by `typology_of`), the Stawisha half is already
            # typology-specific.  Meru 2026-06 -> 195.
            "prep_new_pbfw": {
                "ids": ["S8VvgOzJRkX",   # PREP New BF
                        "KFp4UYTJ4Q6"],  # PREP New PG
                "typology_of": "VIg3ciXYUQn",
                "typology_include": ["preg", "breast"],
                "label": "PrEP New (PBFW)",
            },
            # PBIX `PrEP Initiated ANC` = [PrEP New Total] where
            # 'PrEP Typologies'[PrEP Typologies] = "Pregnant" — i.e. the
            # typology filter over the WHOLE eleven-element PrEP New Total
            # set, with NO separate addition of the standalone Stawisha
            # `PREP New PG` element.  (Pre-2026-09 the spec also summed that
            # element unfiltered, double-counting it: 137 instead of 106 for
            # all counties and 33 instead of 27 for Meru at 2026-06.)
            # The ten Stawisha typology elements carry no 'PrEP Typologies'
            # combos, so the Jamii element alone reproduces the measure.
            "prep_new_preg": {
                "ids": [],                    # no standalone elements
                "typology_of": "VIg3ciXYUQn",  # PrEP_New: PrEP, New Clients
                "typology_include": ["preg"],
                "label": "PrEP New (Pregnant)",
            },
        },
    },
}
